trigger:
  branches:
    include:
    - master
  paths:
    include:
    - challenges/07_azure-devops/*
  
pool:
  vmImage: 'Ubuntu 16.04'
  
steps:
- task: AzureCLI@2
  displayName: Terraform
  inputs:
    azureSubscription: $(service_connection_name)
    scriptType: bash
    scriptLocation: inlineScript
    workingDirectory: ./challenges/02_create-resource-group/solution
    inlineScript: |
      pwd

      terraform init \
        -backend-config="storage_account_name=$(tfstate_storage_account_name)" \
        -backend-config="container_name=$(tfstate_container_name)" \
        -backend-config="key=$(tfstate_key)" \
        -backend-config="access_key=$(tfstate_access_key)"
      
      terraform plan \
        -out=out.tfplan \
        -var 'resource_group_name=$(resource_group_name)' \
        -var 'location=$(location)'
      
      terraform apply out.tfplan -auto-approve